application: howlongtilvegas
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /content
  static_dir: content

- url: /_ah/xmpp/message/chat/
  script: gettime.py

- url: /tasks/sendupdate
  script: sendtime.py

- url: /.*
  static_files: index.html
  upload: index.html
